apiVersion: pubsubplus.solace.com/v1beta1
kind: PubSubPlusEventBroker
metadata:
  namespace: solace-namespace
  name: solace-broker
spec:
  image:
    repository: localhost/solace-pubsub-standard
    tag: latest
    pullPolicy: IfNotPresent
    pullSecrets:
    - name: registry-pull-secret
  adminCredentialsSecret: solace-admin-secret
  redundancy: true
  podDisruptionBudgetForHA: true
  extraEnvVarsSecret: solace-secret-configmap-env
  systemScaling:
    maxConnections: 100
    maxQueueMessages: 100
    maxSpoolUsage: 10000
    messagingNodeCpu: "2"
    messagingNodeMemory: 3410Mi
  storage:
    useStorageClass: solace-storage-class
    messagingNodeStorageSize: 16100Mi
    monitorNodeStorageSize: 2300Mi
  timezone: "Asia/Singapore"
  tls:
    serverTlsConfigSecret: solace-server-secret
    enabled: true
    certFilename: tls.crt
    certKeyFilename: tls.key
  nodeAssignment:
  - name: Primary
    spec:
      tolerations:
      - key: "pkey1"
        operator: "Equal"
        value: "value1"
        effect: "NoExecute"
      - key: "pkey2"
        operator: "Exists"
        effect: "NoExecute"
      - key: "pkey3"
        operator: "Equal"
        value: "value2"
        effect: "NoSchedule"
      nodeSelector:
        pri_key: value
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: pubsubpluseventbroker
              namespaces:
              - solace-namespace
  - name: Backup
    spec:
      tolerations:
      - key: "bkey1"
        operator: "Equal"
        value: "value1"
        effect: "NoExecute"
      - key: "bkey2"
        operator: "Exists"
        effect: "NoSchedule"
      nodeSelector:
        bkp_key: value
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: pubsubpluseventbroker
              namespaces:
              - solace-namespace
  - name: Monitor
    spec:
      tolerations:
      - key: "mkey1"
        operator: "Equal"
        value: "value1"
        effect: "NoExecute"
      - key: "mkey2"
        operator: "Equal"
        value: "value2"
        effect: "NoSchedule"
      nodeSelector:
        mon_key: value
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: pubsubpluseventbroker
              namespaces:
              - solace-namespace
  service:
    type: LoadBalancer
    annotations:
      metallb.universe.tf/loadBalancerIPs: 1.2.3.4
      metallb.io/loadBalancerIPs: 1.2.3.4
      metallb.universe.tf/address-pool: sample-ip-pool
      metallb.io/address-pool: sample-ip-pool
    ports:
    - containerPort: 8080
      name: tcp-semp
      protocol: TCP
      servicePort: 8080
    - containerPort: 1943
      name: tls-semp
      protocol: TCP
      servicePort: 1943
    - containerPort: 55555
      name: tcp-smf
      protocol: TCP
      servicePort: 55555
    - containerPort: 55003
      name: tcp-smfcomp
      protocol: TCP
      servicePort: 55003
    - containerPort: 55443
      name: tls-smf
      protocol: TCP
      servicePort: 55443
    - containerPort: 55556
      name: tcp-smfroute
      protocol: TCP
      servicePort: 55556
    - containerPort: 8008
      name: tcp-web
      protocol: TCP
      servicePort: 8008
    - containerPort: 1443
      name: tls-web
      protocol: TCP
      servicePort: 1443
    - containerPort: 9000
      name: tcp-rest
      protocol: TCP
      servicePort: 9000
    - containerPort: 9443
      name: tls-rest
      protocol: TCP
      servicePort: 9443
    - containerPort: 5672
      name: tcp-amqp
      protocol: TCP
      servicePort: 5672
    - containerPort: 5671
      name: tls-amqp
      protocol: TCP
      servicePort: 5671
    - containerPort: 1883
      name: tcp-mqtt
      protocol: TCP
      servicePort: 1883
    - containerPort: 8883
      name: tls-mqtt
      protocol: TCP
      servicePort: 8883
    - containerPort: 8000
      name: tcp-mqttweb
      protocol: TCP
      servicePort: 8000
    - containerPort: 8443
      name: tls-mqttweb
      protocol: TCP
      servicePort: 8443
